### ISSUE TITLE
How to open a webview using messenger extensions

### ISSUE THREAD

**Issue by akshaygupta1996** [pimax/fb-messenger-php#35] opened 2016-09-25 14:22 UTC

**Comment by ghassen1988** [comment] 2017-01-18 09:30
Did you manage to do it ? I need a webview in my use case

**Comment by akshaygupta1996** [comment] 2017-01-18 09:32
No not yet...i did a other way round.i used flight template instead.

**Comment by ghassen1988** [comment] 2017-01-18 09:40
Oh ... that is not what I am looking for but good for you if it worked . My use case is a payment webview so it need to be configured from scratch

**Comment by wittfabian** [comment] 2017-01-27 10:42
#52

**Comment by ghassen1988** [comment] 2017-01-27 10:50
is there an example how to do it ?

**Comment by wittfabian** [comment] 2017-02-09 11:55
Closed - duplicate of #52

**Closed as completed by wittfabian** 2017-02-09 11:55 UTC
